# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_metrics_double <- function(A, B, Xtrain_csr_p, Xtrain_csr_i, Xtest_csr_p, Xtest_csr_i, Xtest_csr, calc_p_at_k = TRUE, calc_tp_at_k = FALSE, calc_r_at_k = FALSE, calc_ap_at_k = TRUE, calc_tap_at_k = FALSE, calc_ndcg_at_k = TRUE, calc_hit_at_k = FALSE, calc_rr_at_k = FALSE, calc_roc_auc = FALSE, calc_pr_auc = FALSE, k_metrics = 10L, break_ties_with_noise = TRUE, min_pos_test = 1L, min_items_pool = 2L, consider_cold_start = 0L, cumulative = 0L, nthreads = 1L, seed = 1L) {
    .Call(`_recometrics_calc_metrics_double`, A, B, Xtrain_csr_p, Xtrain_csr_i, Xtest_csr_p, Xtest_csr_i, Xtest_csr, calc_p_at_k, calc_tp_at_k, calc_r_at_k, calc_ap_at_k, calc_tap_at_k, calc_ndcg_at_k, calc_hit_at_k, calc_rr_at_k, calc_roc_auc, calc_pr_auc, k_metrics, break_ties_with_noise, min_pos_test, min_items_pool, consider_cold_start, cumulative, nthreads, seed)
}

calc_metrics_float <- function(A, B, Xtrain_csr_p, Xtrain_csr_i, Xtest_csr_p, Xtest_csr_i, Xtest_csr, calc_p_at_k = TRUE, calc_tp_at_k = FALSE, calc_r_at_k = FALSE, calc_ap_at_k = TRUE, calc_tap_at_k = FALSE, calc_ndcg_at_k = TRUE, calc_hit_at_k = FALSE, calc_rr_at_k = FALSE, calc_roc_auc = FALSE, calc_pr_auc = FALSE, k_metrics = 10L, break_ties_with_noise = TRUE, min_pos_test = 1L, min_items_pool = 2L, consider_cold_start = 0L, cumulative = 0L, nthreads = 1L, seed = 1L) {
    .Call(`_recometrics_calc_metrics_float`, A, B, Xtrain_csr_p, Xtrain_csr_i, Xtest_csr_p, Xtest_csr_i, Xtest_csr, calc_p_at_k, calc_tp_at_k, calc_r_at_k, calc_ap_at_k, calc_tap_at_k, calc_ndcg_at_k, calc_hit_at_k, calc_rr_at_k, calc_roc_auc, calc_pr_auc, k_metrics, break_ties_with_noise, min_pos_test, min_items_pool, consider_cold_start, cumulative, nthreads, seed)
}

split_csr_selected_users <- function(X_csr_p, X_csr_i, X_csr, ncols, test_fraction, seed = 1L) {
    .Call(`_recometrics_split_csr_selected_users`, X_csr_p, X_csr_i, X_csr, ncols, test_fraction, seed)
}

split_csr_separated_users <- function(X_csr_p, X_csr_i, X_csr, ncols, n_users_test, test_fraction, consider_cold_start, min_items_pool, min_pos_test, separated, seed = 1L) {
    .Call(`_recometrics_split_csr_separated_users`, X_csr_p, X_csr_i, X_csr, ncols, n_users_test, test_fraction, consider_cold_start, min_items_pool, min_pos_test, separated, seed)
}

C_NAN_to_R_NA <- function(vec) {
    invisible(.Call(`_recometrics_C_NAN_to_R_NA`, vec))
}

R_has_openmp <- function() {
    .Call(`_recometrics_R_has_openmp`)
}

